export const METRICS = [
  {
    acs_fields: ['DP02_0003PE'],
    category: 'HOUSEHOLDS BY TYPE',
    expression: 'DP02_0003PE',
    id: 'families_w_kids',
    name: 'Families with children under 18 years',
  },
  {
    acs_fields: ['DP02_0013PE'],
    category: 'HOUSEHOLDS BY TYPE',
    expression: 'DP02_0013PE',
    id: 'households_w_kids',
    name: 'Households with 1+ people under 18 years',
  },
  {
    acs_fields: ['DP02_0014PE'],
    category: 'HOUSEHOLDS BY TYPE',
    expression: 'DP02_0014PE',
    id: 'households_w_elderly',
    name: 'Households with 1+ people 65 years and over',
  },
  {
    acs_fields: ['DP02_0015E'],
    category: 'HOUSEHOLDS BY TYPE',
    expression: 'DP02_0015E',
    id: 'avg_household_size',
    name: 'Average household size',
  },
  {
    acs_fields: ['DP02_0016E'],
    category: 'HOUSEHOLDS BY TYPE',
    expression: 'DP02_0016E',
    id: 'avg_family_size',
    name: 'Average family size',
  },
  {
    acs_fields: ['DP02_0026E', 'DP02_0032E', 'DP02_0024E', 'DP02_0030E'],
    category: 'MARITAL STATUS',
    expression:
      'round((DP02_0026E + DP02_0032E) / (DP02_0024E + DP02_0030E) * 100, 1)',
    id: 'married',
    name: 'Percent married, 15 years and over',
  },
  {
    acs_fields: ['DP02_0066PE'],
    category: 'EDUCATIONAL ATTAINMENT',
    expression: 'DP02_0066PE',
    id: 'high_school_plus',
    name: 'High school graduate or higher',
  },
  {
    acs_fields: ['DP02_0067PE'],
    category: 'EDUCATIONAL ATTAINMENT',
    expression: 'DP02_0067PE',
    id: 'bach_degree_plus',
    name: "Bachelor's degree or higher",
  },
  {
    acs_fields: ['DP02_0069PE'],
    category: 'VETERAN STATUS',
    expression: 'DP02_0069PE',
    id: 'vets',
    name: 'Civilian veterans',
  },
  {
    acs_fields: ['DP02_0079PE'],
    category: 'RESIDENCE 1 YEAR AGO',
    expression: 'DP02_0079PE',
    id: 'last_yr_same_house',
    name: 'Residence 1 year ago: same house',
  },
  {
    acs_fields: ['DP02_0081PE', 'DP02_0083PE'],
    category: 'RESIDENCE 1 YEAR AGO',
    expression: 'round(DP02_0081PE + DP02_0083PE, 1)',
    id: 'last_yr_diff_house_same_state',
    name: 'Residence 1 year ago: different house, same state',
  },
  {
    acs_fields: ['DP02_0084PE', 'DP02_0085PE'],
    category: 'RESIDENCE 1 YEAR AGO',
    expression: 'round(DP02_0084PE + DP02_0085PE, 1)',
    id: 'last_yr_diff_house_diff_state',
    name: 'Residence 1 year ago: different house, different state',
  },
  {
    acs_fields: ['DP02_0087PE'],
    category: 'PLACE OF BIRTH',
    expression: 'DP02_0087PE',
    id: 'native_born',
    name: 'Native born (US, PR, or abroad to American parents)',
  },
  {
    acs_fields: ['DP02_0092PE'],
    category: 'PLACE OF BIRTH',
    expression: 'DP02_0092PE',
    id: 'foreign_born',
    name: 'Foreign born',
  },
  {
    acs_fields: ['DP02_0089PE'],
    category: 'PLACE OF BIRTH',
    expression: 'DP02_0089PE',
    id: 'born_in_state_of_residence',
    name: 'Born in state of residence',
  },
  {
    acs_fields: ['DP02_0111PE'],
    category: 'LANGUAGE SPOKEN AT HOME',
    expression: 'DP02_0111PE',
    id: 'language_english_only',
    name: 'Language spoken at home: English only',
  },
  {
    acs_fields: ['DP02_0112PE'],
    category: 'LANGUAGE SPOKEN AT HOME',
    expression: 'DP02_0112PE',
    id: 'language_not_english',
    name: 'Language spoken at home: language other than English',
  },
  {
    acs_fields: ['DP02_0123PE'],
    category: 'ANCESTRY',
    expression: 'DP02_0123PE',
    id: 'ancestry_american',
    name: 'Ancestry: American',
  },
  {
    acs_fields: ['DP02_0128PE'],
    category: 'ANCESTRY',
    expression: 'DP02_0128PE',
    id: 'ancestry_english',
    name: 'Ancestry: English',
  },
  {
    acs_fields: ['DP02_0131PE'],
    category: 'ANCESTRY',
    expression: 'DP02_0131PE',
    id: 'ancestry_german',
    name: 'Ancestry: German',
  },
  {
    acs_fields: ['DP02_0134PE'],
    category: 'ANCESTRY',
    expression: 'DP02_0134PE',
    id: 'ancestry_irish',
    name: 'Ancestry: Irish',
  },
  {
    acs_fields: ['DP02_0135PE'],
    category: 'ANCESTRY',
    expression: 'DP02_0135PE',
    id: 'ancestry_italian',
    name: 'Ancestry: Italian',
  },
  {
    acs_fields: ['DP03_0009PE'],
    category: 'EMPLOYMENT STATUS',
    expression: 'DP03_0009PE',
    id: 'unemployment_rate',
    name: 'Unemployment rate',
  },
  {
    acs_fields: ['DP03_0021PE'],
    category: 'COMMUTING TO WORK',
    expression: 'DP03_0021PE',
    id: 'commute_via_public_transport',
    name: 'Commute to work via public transportation',
  },
  {
    acs_fields: ['DP03_0024PE'],
    category: 'COMMUTING TO WORK',
    expression: 'DP03_0024PE',
    id: 'work_at_home',
    name: 'Work at home',
  },
  {
    acs_fields: ['DP03_0025E'],
    category: 'COMMUTING TO WORK',
    expression: 'DP03_0025E',
    id: 'travel_time_to_work',
    name: 'Mean travel time to work (minutes)',
  },
  {
    acs_fields: ['DP03_0042PE'],
    category: 'INDUSTRY',
    expression: 'DP03_0042PE',
    id: 'industry_edu_healthcare_social',
    name:
      'Industry: Educational services, and health care and social assistance',
  },
  {
    acs_fields: ['DP03_0037PE'],
    category: 'INDUSTRY',
    expression: 'DP03_0037PE',
    id: 'industry_retail_trade',
    name: 'Industry: Retail trade',
  },
  {
    acs_fields: ['DP03_0041PE'],
    category: 'INDUSTRY',
    expression: 'DP03_0041PE',
    id: 'industry_prof_science_manage',
    name:
      'Industry: Professional, scientific, and management, and administrative and waste management services',
  },
  {
    acs_fields: ['DP03_0035PE'],
    category: 'INDUSTRY',
    expression: 'DP03_0035PE',
    id: 'industry_manufacturing',
    name: 'Industry: Manufacturing',
  },
  {
    acs_fields: ['DP03_0043PE'],
    category: 'INDUSTRY',
    expression: 'DP03_0043PE',
    id: 'industry_arts_rec_food',
    name:
      'Industry: Arts, entertainment, and recreation, and accommodation and food services',
  },
  {
    acs_fields: [
      'DP03_0042PE',
      'DP03_0037PE',
      'DP03_0041PE',
      'DP03_0035PE',
      'DP03_0043PE',
    ],
    category: 'INDUSTRY',
    expression:
      'round(100 - (DP03_0042PE + DP03_0037PE + DP03_0041PE + DP03_0035PE + DP03_0043PE), 1)',
    id: 'industry_other',
    name: 'Industry: Other',
  },
  {
    acs_fields: ['DP03_0062E'],
    category: 'INCOME AND BENEFITS',
    expression: 'DP03_0062E',
    id: 'median_household_income',
    name: 'Median household income',
  },
  {
    acs_fields: ['DP03_0063E'],
    category: 'INCOME AND BENEFITS',
    expression: 'DP03_0063E',
    id: 'mean_household_income',
    name: 'Mean household income',
  },
  {
    acs_fields: ['DP03_0086E'],
    category: 'INCOME AND BENEFITS',
    expression: 'DP03_0086E',
    id: 'median_family_income',
    name: 'Median family income',
  },
  {
    acs_fields: ['DP03_0087E'],
    category: 'INCOME AND BENEFITS',
    expression: 'DP03_0087E',
    id: 'mean_family_income',
    name: 'Mean family income',
  },
  {
    acs_fields: ['DP03_0096PE'],
    category: 'HEALTH INSURANCE COVERAGE',
    expression: 'DP03_0096PE',
    id: 'health_coverage',
    name: 'People with health insurance coverage',
  },
  {
    acs_fields: ['DP03_0119PE'],
    category:
      'PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL',
    expression: 'DP03_0119PE',
    id: 'families_poverty',
    name: 'Families with income below poverty level',
  },
  {
    acs_fields: ['DP04_0037E'],
    category: 'ROOMS',
    expression: 'DP04_0037E',
    id: 'median_rooms',
    name: 'Median rooms',
  },
  {
    acs_fields: ['DP04_0046PE'],
    category: 'HOUSING TENURE',
    expression: 'DP04_0046PE',
    id: 'owner_occupied',
    name: 'Owner-occupied',
  },
  {
    acs_fields: ['DP04_0047PE'],
    category: 'HOUSING TENURE',
    expression: 'DP04_0047PE',
    id: 'renter_occupied',
    name: 'Renter-occupied',
  },
  {
    acs_fields: ['DP04_0089E'],
    category: 'VALUE',
    expression: 'DP04_0089E',
    id: 'median_house_value',
    name: 'Median value, Owner-occupied units',
  },
  {
    acs_fields: ['DP04_0088PE'],
    category: 'VALUE',
    expression: 'DP04_0088PE',
    id: 'houses_million_plus',
    name: 'Percent of houses valued at $1M+',
  },
  {
    acs_fields: ['DP04_0101E'],
    category: 'SELECTED MONTHLY OWNER COSTS (SMOC)',
    expression: 'DP04_0101E',
    id: 'mortgage_monthly_costs',
    name: 'Median monthly owner costs (with mortgage)',
  },
  {
    acs_fields: ['DP04_0134E'],
    category: 'GROSS RENT',
    expression: 'DP04_0134E',
    id: 'rent_monthly_costs',
    name: 'Median cost, occupied units paying rent',
  },
  {
    acs_fields: ['DP05_0017E'],
    category: 'SEX AND AGE',
    expression: 'DP05_0017E',
    id: 'median_age',
    name: 'Median age (years)',
  },
  {
    acs_fields: ['DP05_0019PE'],
    category: 'SEX AND AGE',
    expression: 'DP05_0019PE',
    id: '_21_and_over',
    name: '21 years and over',
  },
  {
    acs_fields: ['DP05_0021PE'],
    category: 'SEX AND AGE',
    expression: 'DP05_0021PE',
    id: '_65_and_over',
    name: '65 years and over',
  },
  {
    acs_fields: ['DP05_0059PE'],
    category: 'RACE',
    expression: 'DP05_0059PE',
    id: 'white',
    name: 'Percent White',
  },
  {
    acs_fields: ['DP05_0060PE'],
    category: 'RACE',
    expression: 'DP05_0060PE',
    id: 'black',
    name: 'Percent Black or African American',
  },
  {
    acs_fields: ['DP05_0062PE'],
    category: 'RACE',
    expression: 'DP05_0062PE',
    id: 'asian',
    name: 'Percent Asian',
  },
  {
    acs_fields: ['DP05_0059PE', 'DP05_0060PE', 'DP05_0062PE'],
    category: 'RACE',
    expression: 'round(100 - (DP05_0059PE + DP05_0060PE + DP05_0062PE), 1)',
    id: 'other_race',
    name: 'Percent some other race',
  },
  {
    acs_fields: ['DP05_0066PE'],
    category: 'HISPANIC OR LATINO AND RACE',
    expression: 'DP05_0066PE',
    id: 'hispanic_latino',
    name: 'Hispanic or Latino',
  },
]
